var currencies = [
  {
    iso: 'AD',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Andorra',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'AE',
    currency: 'AED',
    symbol: 'د.إ',
    countryName: 'United Arab Emirates',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'AF',
    currency: 'AFN',
    symbol: '؋',
    countryName: 'Afghanistan',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'AG',
    currency: 'XCD',
    symbol: '$',
    countryName: 'Antigua and Barbuda',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'AI',
    currency: 'XCD',
    symbol: '$',
    countryName: 'Anguilla',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'AL',
    currency: 'ALL',
    symbol: 'L',
    countryName: 'Albania',
    dateFormat: 'yyyy-MM-dd',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'AM',
    currency: 'AMD',
    symbol: 'Դ',
    countryName: 'Armenia',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'AO',
    currency: 'AOA',
    symbol: 'Kz',
    countryName: 'Angola',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'AR',
    currency: 'ARS',
    symbol: '$',
    countryName: 'Argentina',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'AS',
    currency: 'USD',
    symbol: '$',
    countryName: 'American Samoa',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'AT',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Austria',
    dateFormat: 'dd.MM.yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'AU',
    currency: 'AUD',
    symbol: '$',
    countryName: 'Australia',
    dateFormat: 'd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'AW',
    currency: 'AWG',
    symbol: 'ƒ',
    countryName: 'Aruba',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'AX',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Aland Islands',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'AZ',
    currency: 'AZN',
    symbol: '₼',
    countryName: 'Azerbaijan',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'BA',
    currency: 'BAM',
    symbol: 'KM',
    countryName: 'Bosnia and Herzegovina',
    dateFormat: 'yyyy-MM-dd',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'BB',
    currency: 'BBD',
    symbol: '$',
    countryName: 'Barbados',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'BD',
    currency: 'BDT',
    symbol: '৳',
    countryName: 'Bangladesh',
    thousandsSeparator: ',',
    decimalDigits: 0,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'BE',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Belgium',
    dateFormat: 'd/MM/yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'BF',
    currency: 'XOF',
    symbol: 'CFA',
    countryName: 'Burkina Faso',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'BG',
    currency: 'BGN',
    symbol: 'Лв.',
    countryName: 'Bulgaria',
    dateFormat: 'yyyy-M-d',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'BH',
    currency: 'BHD',
    symbol: ' د.ب‎',
    countryName: 'Bahrain',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 3,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'BI',
    currency: 'BIF',
    symbol: 'FBu',
    countryName: 'Burundi',
    thousandsSeparator: ',',
    decimalDigits: 0,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'BJ',
    currency: 'XOF',
    symbol: 'CFA',
    countryName: 'Benin',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'BL',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Saint Barthelemy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'BM',
    currency: 'BMD',
    symbol: '$',
    countryName: 'Bermuda',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'BN',
    currency: 'BND',
    symbol: '$',
    countryName: 'Brunei',
    thousandsSeparator: '.',
    decimalDigits: 0,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'BO',
    currency: 'BOB',
    symbol: 'Bs',
    countryName: 'Bolivia',
    dateFormat: 'dd-MM-yyyy',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'BQ',
    currency: 'USD',
    symbol: '$',
    countryName: 'Bonaire, Saint Eustatius and Saba ',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'BR',
    currency: 'BRL',
    symbol: 'R$',
    countryName: 'Brazil',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'BS',
    currency: 'BSD',
    symbol: 'BSD',
    countryName: 'Bahamas',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'BT',
    currency: 'BTN',
    symbol: 'BTN',
    countryName: 'Bhutan',
    thousandsSeparator: ',',
    decimalDigits: 1,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'BV',
    currency: 'NOK',
    symbol: 'Nkr',
    countryName: 'Bouvet Island',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'BW',
    currency: 'BWP',
    symbol: 'BWP',
    countryName: 'Botswana',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'BY',
    currency: 'BYN',
    symbol: 'BYN',
    countryName: 'Belarus',
    dateFormat: 'd.M.yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'BZ',
    currency: 'BZD',
    symbol: '$',
    countryName: 'Belize',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'CA',
    currency: 'CAD',
    symbol: '$',
    countryName: 'Canada',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'CC',
    currency: 'AUD',
    symbol: '$',
    countryName: 'Cocos Islands',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'CD',
    currency: 'CDF',
    symbol: 'CDF',
    countryName: 'Democratic Republic of the Congo',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'CF',
    currency: 'XAF',
    symbol: 'FCFA',
    countryName: 'Central African Republic',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'CG',
    currency: 'XAF',
    symbol: 'FCFA',
    countryName: 'Republic of the Congo',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'CH',
    currency: 'CHF',
    symbol: 'CHF',
    countryName: 'Switzerland',
    dateFormat: 'dd.MM.yyyy',
    thousandsSeparator: "'",
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'CI',
    currency: 'XOF',
    symbol: 'CFA',
    countryName: 'Ivory Coast',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'CK',
    currency: 'NZD',
    symbol: '$',
    countryName: 'Cook Islands',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'CL',
    currency: 'CLP',
    symbol: '$',
    countryName: 'Chile',
    dateFormat: 'dd-MM-yyyy',
    thousandsSeparator: '.',
    decimalDigits: 0,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'CM',
    currency: 'XAF',
    symbol: 'FCFA',
    countryName: 'Cameroon',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'CN',
    currency: 'CNY',
    symbol: '¥',
    countryName: 'China',
    dateFormat: 'yyyy-M-d',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'CO',
    currency: 'COP',
    symbol: '$',
    countryName: 'Colombia',
    dateFormat: 'd/MM/yyyy',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'CR',
    currency: 'CRC',
    symbol: '₡',
    countryName: 'Costa Rica',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'CU',
    currency: 'CUP',
    symbol: 'CUP',
    countryName: 'Cuba',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'CV',
    currency: 'CVE',
    symbol: '$',
    countryName: 'Cape Verde',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'CW',
    currency: 'ANG',
    symbol: 'ANG',
    countryName: 'Curacao',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'CX',
    currency: 'AUD',
    symbol: '$',
    countryName: 'Christmas Island',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'CY',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Cyprus',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'CZ',
    currency: 'CZK',
    symbol: 'Kč',
    countryName: 'Czech Republic',
    dateFormat: 'd.M.yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'DE',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Germany',
    dateFormat: 'dd.MM.yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'DJ',
    currency: 'DJF',
    symbol: 'Fdj',
    countryName: 'Djibouti',
    thousandsSeparator: ',',
    decimalDigits: 0,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'DK',
    currency: 'DKK',
    symbol: 'Kr.',
    countryName: 'Denmark',
    dateFormat: 'dd-MM-yyyy',
    thousandsSeparator: '',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'DM',
    currency: 'XCD',
    symbol: 'XCD',
    countryName: 'Dominica',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'DO',
    currency: 'DOP',
    symbol: '$',
    countryName: 'Dominican Republic',
    dateFormat: 'MM/dd/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'DZ',
    currency: 'DZD',
    symbol: 'DA',
    countryName: 'Algeria',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'EC',
    currency: 'USD',
    symbol: '$',
    countryName: 'Ecuador',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'EE',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Estonia',
    dateFormat: 'd.MM.yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'EG',
    currency: 'EGP',
    symbol: 'E£',
    countryName: 'Egypt',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'EH',
    currency: 'MAD',
    symbol: 'MAD',
    countryName: 'Western Sahara',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'ER',
    currency: 'ERN',
    symbol: 'Nfk',
    countryName: 'Eritrea',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'ES',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Spain',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'ET',
    currency: 'ETB',
    symbol: 'Br',
    countryName: 'Ethiopia',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'FI',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Finland',
    dateFormat: 'd.M.yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'FJ',
    currency: 'FJD',
    symbol: 'FJD',
    countryName: 'Fiji',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'FK',
    currency: 'FKP',
    symbol: 'FKP',
    countryName: 'Falkland Islands',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'FM',
    currency: 'USD',
    symbol: '$',
    countryName: 'Micronesia',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'FO',
    currency: 'DKK',
    symbol: 'Dkr',
    countryName: 'Faroe Islands',
    thousandsSeparator: '',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'FR',
    currency: 'EUR',
    symbol: '€',
    countryName: 'France',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'GA',
    currency: 'XAF',
    symbol: 'FCFA',
    countryName: 'Gabon',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'GB',
    currency: 'GBP',
    symbol: '£',
    countryName: 'United Kingdom',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'GD',
    currency: 'XCD',
    symbol: 'XCD',
    countryName: 'Grenada',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'GE',
    currency: 'GEL',
    symbol: 'GEL',
    countryName: 'Georgia',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'GF',
    currency: 'EUR',
    symbol: '€',
    countryName: 'French Guiana',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'GG',
    currency: 'GBP',
    symbol: '£',
    countryName: 'Guernsey',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'GH',
    currency: 'GHS',
    symbol: 'GH₵',
    countryName: 'Ghana',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'GI',
    currency: 'GIP',
    symbol: 'GIP',
    countryName: 'Gibraltar',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'GL',
    currency: 'DKK',
    symbol: 'Dkr',
    countryName: 'Greenland',
    thousandsSeparator: '',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'GM',
    currency: 'GMD',
    symbol: 'GMD',
    countryName: 'Gambia',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'GN',
    currency: 'GNF',
    symbol: 'FG',
    countryName: 'Guinea',
    thousandsSeparator: ',',
    decimalDigits: 0,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'GP',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Guadeloupe',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'GQ',
    currency: 'XAF',
    symbol: 'FCFA',
    countryName: 'Equatorial Guinea',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'GR',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Greece',
    dateFormat: 'd/M/yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'GS',
    currency: 'GBP',
    symbol: '£',
    countryName: 'South Georgia and the South Sandwich Islands',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'GT',
    currency: 'GTQ',
    symbol: 'GTQ',
    countryName: 'Guatemala',
    dateFormat: 'd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'GU',
    currency: 'USD',
    symbol: '$',
    countryName: 'Guam',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'GW',
    currency: 'XOF',
    symbol: 'CFA',
    countryName: 'Guinea-Bissau',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'GY',
    currency: 'GYD',
    symbol: 'GYD',
    countryName: 'Guyana',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'HK',
    currency: 'HKD',
    symbol: 'HK$',
    countryName: 'Hong Kong',
    dateFormat: 'yyyy年M月d日',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'HM',
    currency: 'AUD',
    symbol: '$',
    countryName: 'Heard Island and McDonald Islands',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'HN',
    currency: 'HNL',
    symbol: 'HNL',
    countryName: 'Honduras',
    dateFormat: 'MM-dd-yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'HR',
    currency: 'HRK',
    symbol: 'kn',
    countryName: 'Croatia',
    dateFormat: 'dd.MM.yyyy.',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'HT',
    currency: 'HTG',
    symbol: 'HTG',
    countryName: 'Haiti',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'HU',
    currency: 'HUF',
    symbol: 'Ft',
    countryName: 'Hungary',
    dateFormat: 'yyyy.MM.dd.',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'ID',
    currency: 'IDR',
    symbol: 'Rp',
    countryName: 'Indonesia',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: '.',
    decimalDigits: 0,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'IE',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Ireland',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'IL',
    currency: 'ILS',
    symbol: '₪',
    countryName: 'Israel',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'IM',
    currency: 'GBP',
    symbol: '£',
    countryName: 'Isle of Man',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'IN',
    currency: 'INR',
    symbol: 'Rs',
    countryName: 'India',
    dateFormat: 'd/M/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'IO',
    currency: 'USD',
    symbol: '$',
    countryName: 'British Indian Ocean Territory',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'IQ',
    currency: 'IQD',
    symbol: 'IQD',
    countryName: 'Iraq',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'IR',
    currency: 'IRR',
    symbol: 'IRR',
    countryName: 'Iran',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '/',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'IS',
    currency: 'ISK',
    symbol: 'Ikr',
    countryName: 'Iceland',
    dateFormat: 'd.M.yyyy',
    thousandsSeparator: '.',
    decimalDigits: 0,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'IT',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Italy',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'JE',
    currency: 'GBP',
    symbol: '£',
    countryName: 'Jersey',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'JM',
    currency: 'JMD',
    symbol: '$',
    countryName: 'Jamaica',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'JO',
    currency: 'JOD',
    symbol: 'JD',
    countryName: 'Jordan',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 3,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'JP',
    currency: 'JPY',
    symbol: '¥',
    countryName: 'Japan',
    dateFormat: 'H24.MM.dd',
    thousandsSeparator: ',',
    decimalDigits: 0,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'KE',
    currency: 'KES',
    symbol: 'Ksh',
    countryName: 'Kenya',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'KG',
    currency: 'KGS',
    symbol: 'KGS',
    countryName: 'Kyrgyzstan',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: '-',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'KH',
    currency: 'KHR',
    symbol: 'KHR',
    countryName: 'Cambodia',
    thousandsSeparator: ',',
    decimalDigits: 0,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'KI',
    currency: 'AUD',
    symbol: '$',
    countryName: 'Kiribati',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'KM',
    currency: 'KMF',
    symbol: 'CF',
    countryName: 'Comoros',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'KN',
    currency: 'XCD',
    symbol: 'XCD',
    countryName: 'Saint Kitts and Nevis',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'KP',
    currency: 'KPW',
    symbol: 'KPW',
    countryName: 'North Korea',
    thousandsSeparator: ',',
    decimalDigits: 0,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'KR',
    currency: 'KRW',
    symbol: '₩',
    countryName: 'South Korea',
    dateFormat: 'yyyy. M. d',
    thousandsSeparator: ',',
    decimalDigits: 0,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'KW',
    currency: 'KWD',
    symbol: 'KD',
    countryName: 'Kuwait',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 3,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'KY',
    currency: 'KYD',
    symbol: 'KYD',
    countryName: 'Cayman Islands',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'KZ',
    currency: 'KZT',
    symbol: 'KZT',
    countryName: 'Kazakhstan',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: '-',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'LA',
    currency: 'LAK',
    symbol: 'LAK',
    countryName: 'Laos',
    thousandsSeparator: ',',
    decimalDigits: 0,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'LB',
    currency: 'LBP',
    symbol: '£',
    countryName: 'Lebanon',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'LC',
    currency: 'XCD',
    symbol: 'XCD',
    countryName: 'Saint Lucia',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'LI',
    currency: 'CHF',
    symbol: 'CHF',
    countryName: 'Liechtenstein',
    thousandsSeparator: "'",
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'LK',
    currency: 'LKR',
    symbol: 'SLRs',
    countryName: 'Sri Lanka',
    thousandsSeparator: ',',
    decimalDigits: 0,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'LR',
    currency: 'LRD',
    symbol: 'LRD',
    countryName: 'Liberia',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'LS',
    currency: 'LSL',
    symbol: 'LSL',
    countryName: 'Lesotho',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'LT',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Lithuania',
    dateFormat: 'yyyy.M.d',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'LU',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Luxembourg',
    dateFormat: 'dd.MM.yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'LV',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Latvia',
    dateFormat: 'yyyy.d.M',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'LY',
    currency: 'LYD',
    symbol: 'LD',
    countryName: 'Libya',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 3,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'MA',
    currency: 'MAD',
    symbol: 'MAD',
    countryName: 'Morocco',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'MC',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Monaco',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'MD',
    currency: 'MDL',
    symbol: 'MDL',
    countryName: 'Moldova',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'ME',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Montenegro',
    dateFormat: 'd.M.yyyy.',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'MF',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Saint Martin',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'MG',
    currency: 'MGA',
    symbol: 'MGA',
    countryName: 'Madagascar',
    thousandsSeparator: ',',
    decimalDigits: 0,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'MH',
    currency: 'USD',
    symbol: '$',
    countryName: 'Marshall Islands',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'MK',
    currency: 'MKD',
    symbol: 'MKD',
    countryName: 'Macedonia',
    dateFormat: 'd.M.yyyy',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'ML',
    currency: 'XOF',
    symbol: 'CFA',
    countryName: 'Mali',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'MM',
    currency: 'MMK',
    symbol: 'MMK',
    countryName: 'Myanmar',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'MN',
    currency: 'MNT',
    symbol: 'MNT',
    countryName: 'Mongolia',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'MO',
    currency: 'MOP',
    symbol: '$',
    countryName: 'Macao',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'MP',
    currency: 'USD',
    symbol: '$',
    countryName: 'Northern Mariana Islands',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'MQ',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Martinique',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'MR',
    currency: 'MRU',
    symbol: 'MRU',
    countryName: 'Mauritania',
  },
  {
    iso: 'MS',
    currency: 'XCD',
    symbol: 'XCD',
    countryName: 'Montserrat',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'MT',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Malta',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'MU',
    currency: 'MUR',
    symbol: 'MURs',
    countryName: 'Mauritius',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'MV',
    currency: 'MVR',
    symbol: 'MVR',
    countryName: 'Maldives',
    thousandsSeparator: ',',
    decimalDigits: 1,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'MW',
    currency: 'MWK',
    symbol: 'MWK',
    countryName: 'Malawi',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'MX',
    currency: 'MXN',
    symbol: '$',
    countryName: 'Mexico',
    dateFormat: 'd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'MY',
    currency: 'MYR',
    symbol: 'RM',
    countryName: 'Malaysia',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'MZ',
    currency: 'MZN',
    symbol: 'MTn',
    countryName: 'Mozambique',
    thousandsSeparator: ',',
    decimalDigits: 0,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'NA',
    currency: 'NAD',
    symbol: '$',
    countryName: 'Namibia',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'NC',
    currency: 'XPF',
    symbol: 'XPF',
    countryName: 'New Caledonia',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'NE',
    currency: 'XOF',
    symbol: 'CFA',
    countryName: 'Niger',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'NF',
    currency: 'AUD',
    symbol: '$',
    countryName: 'Norfolk Island',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'NG',
    currency: 'NGN',
    symbol: '₦',
    countryName: 'Nigeria',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'NI',
    currency: 'NIO',
    symbol: '$',
    countryName: 'Nicaragua',
    dateFormat: 'MM-dd-yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'NL',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Netherlands',
    dateFormat: 'd-M-yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'NO',
    currency: 'NOK',
    symbol: 'Nkr',
    countryName: 'Norway',
    dateFormat: 'dd.MM.yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'NP',
    currency: 'NPR',
    symbol: 'NPRs',
    countryName: 'Nepal',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'NR',
    currency: 'AUD',
    symbol: '$',
    countryName: 'Nauru',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'NU',
    currency: 'NZD',
    symbol: '$',
    countryName: 'Niue',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'NZ',
    currency: 'NZD',
    symbol: '$',
    countryName: 'New Zealand',
    dateFormat: 'd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'OM',
    currency: 'OMR',
    symbol: 'OMR',
    countryName: 'Oman',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 3,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'PA',
    currency: 'PAB',
    symbol: 'B/.',
    countryName: 'Panama',
    dateFormat: 'MM/dd/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'PE',
    currency: 'PEN',
    symbol: 'S/.',
    countryName: 'Peru',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'PF',
    currency: 'XPF',
    symbol: 'XPF',
    countryName: 'French Polynesia',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'PG',
    currency: 'PGK',
    symbol: 'PGK',
    countryName: 'Papua New Guinea',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'PH',
    currency: 'PHP',
    symbol: '₱',
    countryName: 'Philippines',
    dateFormat: 'M/d/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'PK',
    currency: 'PKR',
    symbol: 'PKRs',
    countryName: 'Pakistan',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'PL',
    currency: 'PLN',
    symbol: 'zł',
    countryName: 'Poland',
    dateFormat: 'dd.MM.yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'PM',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Saint Pierre and Miquelon',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'PN',
    currency: 'NZD',
    symbol: '$',
    countryName: 'Pitcairn',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'PR',
    currency: 'USD',
    symbol: '$',
    countryName: 'Puerto Rico',
    dateFormat: 'MM-dd-yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'PS',
    currency: 'ILS',
    symbol: '₪',
    countryName: 'Palestinian Territory',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'PT',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Portugal',
    dateFormat: 'dd-MM-yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'PW',
    currency: 'USD',
    symbol: '$',
    countryName: 'Palau',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'PY',
    currency: 'PYG',
    symbol: '₲',
    countryName: 'Paraguay',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'QA',
    currency: 'QAR',
    symbol: 'QR',
    countryName: 'Qatar',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'RE',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Reunion',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'RO',
    currency: 'RON',
    symbol: 'RON',
    countryName: 'Romania',
    dateFormat: 'dd.MM.yyyy',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'RS',
    currency: 'RSD',
    symbol: 'din.',
    countryName: 'Serbia',
    dateFormat: 'd.M.yyyy.',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'RU',
    currency: 'RUB',
    symbol: 'RUB',
    countryName: 'Russia',
    dateFormat: 'dd.MM.yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'RW',
    currency: 'RWF',
    symbol: 'RWF',
    countryName: 'Rwanda',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'SA',
    currency: 'SAR',
    symbol: 'SR',
    countryName: 'Saudi Arabia',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'SB',
    currency: 'SBD',
    symbol: 'SBD',
    countryName: 'Solomon Islands',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'SC',
    currency: 'SCR',
    symbol: 'SCR',
    countryName: 'Seychelles',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'SD',
    currency: 'SDG',
    symbol: 'SDG',
    countryName: 'Sudan',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'SE',
    currency: 'SEK',
    symbol: 'Skr',
    countryName: 'Sweden',
    dateFormat: 'yyyy-MM-dd',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'SG',
    currency: 'SGD',
    symbol: '$',
    countryName: 'Singapore',
    dateFormat: 'M/d/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'SH',
    currency: 'SHP',
    symbol: 'SHP',
    countryName: 'Saint Helena',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'SI',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Slovenia',
    dateFormat: 'd.M.yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'SJ',
    currency: 'NOK',
    symbol: 'Nkr',
    countryName: 'Svalbard and Jan Mayen',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'SK',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Slovakia',
    dateFormat: 'd.M.yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'SL',
    currency: 'SLL',
    symbol: 'SLL',
    countryName: 'Sierra Leone',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'SM',
    currency: 'EUR',
    symbol: '€',
    countryName: 'San Marino',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'SN',
    currency: 'XOF',
    symbol: 'CFA',
    countryName: 'Senegal',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'SO',
    currency: 'SOS',
    symbol: 'Ssh',
    countryName: 'Somalia',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'SR',
    currency: 'SRD',
    symbol: 'SRD',
    countryName: 'Suriname',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'SS',
    currency: 'SSP',
    symbol: 'SSP',
    countryName: 'South Sudan',
  },
  {
    iso: 'ST',
    currency: 'STD',
    symbol: 'STD',
    countryName: 'Sao Tome and Principe',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'SV',
    currency: 'USD',
    symbol: '$',
    countryName: 'El Salvador',
    dateFormat: 'MM-dd-yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'SX',
    currency: 'ANG',
    symbol: 'ANG',
    countryName: 'Sint Maarten',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'SY',
    currency: 'SYP',
    symbol: 'SY£',
    countryName: 'Syria',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'SZ',
    currency: 'SZL',
    symbol: 'SZL',
    countryName: 'Swaziland',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'TC',
    currency: 'USD',
    symbol: '$',
    countryName: 'Turks and Caicos Islands',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'TD',
    currency: 'XAF',
    symbol: 'FCFA',
    countryName: 'Chad',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'TF',
    currency: 'EUR',
    symbol: '€',
    countryName: 'French Southern Territories',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'TG',
    currency: 'XOF',
    symbol: 'CFA',
    countryName: 'Togo',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'TH',
    currency: 'THB',
    symbol: '฿',
    countryName: 'Thailand',
    dateFormat: '๓/๖/๒๕๕๕',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'TJ',
    currency: 'TJS',
    symbol: 'TJS',
    countryName: 'Tajikistan',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ';',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'TK',
    currency: 'NZD',
    symbol: '$',
    countryName: 'Tokelau',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'TL',
    currency: 'USD',
    symbol: '$',
    countryName: 'East Timor',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'TM',
    currency: 'TMT',
    symbol: 'TMT',
    countryName: 'Turkmenistan',
    thousandsSeparator: ' ',
    decimalDigits: 0,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'TN',
    currency: 'TND',
    symbol: 'DT',
    countryName: 'Tunisia',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 3,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'TO',
    currency: 'TOP',
    symbol: '$',
    countryName: 'Tonga',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'TR',
    currency: 'TRY',
    symbol: 'TL',
    countryName: 'Turkey',
    dateFormat: 'dd.MM.yyyy',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'TT',
    currency: 'TTD',
    symbol: '$',
    countryName: 'Trinidad and Tobago',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'TV',
    currency: 'AUD',
    symbol: '$',
    countryName: 'Tuvalu',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'TW',
    currency: 'TWD',
    symbol: '$',
    countryName: 'Taiwan',
    dateFormat: 'yyyy/M/d',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'TZ',
    currency: 'TZS',
    symbol: 'TSh',
    countryName: 'Tanzania',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'UA',
    currency: 'UAH',
    symbol: '₴',
    countryName: 'Ukraine',
    dateFormat: 'dd.MM.yyyy',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'UG',
    currency: 'UGX',
    symbol: 'USh',
    countryName: 'Uganda',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'UM',
    currency: 'USD',
    symbol: '$',
    countryName: 'United States Minor Outlying Islands',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'US',
    currency: 'USD',
    symbol: '$',
    countryName: 'United States',
    dateFormat: 'M/d/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'UY',
    currency: 'UYU',
    symbol: '$',
    countryName: 'Uruguay',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'UZ',
    currency: 'UZS',
    symbol: 'UZS',
    countryName: 'Uzbekistan',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'VA',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Vatican',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'VC',
    currency: 'XCD',
    symbol: 'XCD',
    countryName: 'Saint Vincent and the Grenadines',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'VE',
    currency: 'VEF',
    symbol: 'Bs.F.',
    countryName: 'Venezuela',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: '.',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'VG',
    currency: 'USD',
    symbol: '$',
    countryName: 'British Virgin Islands',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'VI',
    currency: 'USD',
    symbol: '$',
    countryName: 'U.S. Virgin Islands',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'VN',
    currency: 'VND',
    symbol: '₫',
    countryName: 'Vietnam',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: '.',
    decimalDigits: 0,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'VU',
    currency: 'VUV',
    symbol: 'VUV',
    countryName: 'Vanuatu',
    thousandsSeparator: ',',
    decimalDigits: 0,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'WF',
    currency: 'XPF',
    symbol: 'XPF',
    countryName: 'Wallis and Futuna',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'WS',
    currency: 'WST',
    symbol: 'WST',
    countryName: 'Samoa',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'XK',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Kosovo',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'YE',
    currency: 'YER',
    symbol: 'YR',
    countryName: 'Yemen',
    dateFormat: 'dd/MM/yyyy',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'YT',
    currency: 'EUR',
    symbol: '€',
    countryName: 'Mayotte',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: false,
    spaceBetweenAmountAndSymbol: true,
  },
  {
    iso: 'ZA',
    currency: 'ZAR',
    symbol: 'R',
    countryName: 'South Africa',
    dateFormat: 'yyyy/MM/dd',
    thousandsSeparator: ' ',
    decimalDigits: 2,
    decimalSeparator: ',',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'ZM',
    currency: 'ZMW',
    symbol: 'ZK',
    countryName: 'Zambia',
    thousandsSeparator: ',',
    decimalDigits: 2,
    decimalSeparator: '.',
    symbolOnLeft: true,
    spaceBetweenAmountAndSymbol: false,
  },
  {
    iso: 'ZW',
    currency: 'ZWL',
    symbol: 'ZWL',
    countryName: 'Zimbabwe',
  },
];
